name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Populate docker-compose with ENV
        uses: danielr1996/envsubst-action@1.1.0
        env:
          NGINX_HOST: {{ vars.SERVER_HOST }}
          DB_PASS: {{ secrets.DB_PASS }}
          DB_USER: {{ secrets.DB_USER }}
          DB_NAME: {{ vars.DB_NAME }}
        with:
          input: docker-compose.yml
          output: docker-compose.yml

      - name: SCP docker-compose
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.SERVER_HOST }}
          port: 22
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: ./*
          target: ~/wordpress

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.SERVER_HOST }}
          port: 22
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: cd ~/wordpress && docker-compose up -d && docker system prune -af
